version: '3'

services:

  kali:
    image: estopl/kali:ssh
    tty: true
    ports:
      - "2222:22"
    cap_add:
      - NET_ADMIN
    command: bash -c "service ssh start && tail -f /dev/null"
    working_dir: /home/kali
    volumes:
      - ./volumes/kali:/home/kali
    networks:
      testing_net:
        ipv4_address: 172.19.0.8

  mutillidae_db:
    image: mysql:5.5
    environment:
        MYSQL_ROOT_PASSWORD: mutillidae
        MYSQL_DATABASE: mutillidae
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    volumes:
      - ./volumes/muti_db_data:/var/lib/mysql
    networks:
      testing_net:
        ipv4_address: 172.19.1.10

  mutillidae_web:
    image: crhystamils/mutillidae
    links:
        - mutillidae_db
    depends_on:
        - mutillidae_db
    networks:
      testing_net:
        ipv4_address: 172.19.1.3

  dvwa_db:
    image: mysql:5
    volumes:
      - ./volumes/dvwa_db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    networks:
      testing_net:
        ipv4_address: 172.19.1.9

  web_dvwa:
    image: vulnerables/web-dvwa
    links:
        - dvwa_db
    depends_on:
        - dvwa_db
    networks:
      testing_net:
        ipv4_address: 172.19.1.4

  juice_shop:
    image: bkimminich/juice-shop
    networks:
      testing_net:
        ipv4_address: 172.19.1.5

  wordpress_db:
    image: mysql:5
    volumes:
      - ./volumes/wordpress_db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    networks:
      testing_net:
        ipv4_address: 172.19.1.7

  wordpress:
    image: estopl/wordpress:laura
    links:
        - wordpress_db
    depends_on:
        - wordpress_db
    volumes:
      - ./volumes/wordpress_data:/var/www/html
    environment: 
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8080:80"
    networks:
      testing_net:
        ipv4_address: 172.19.1.6

  metasploitable2:
    tty: true
    image: estopl/metasploitable2-testing:latest
    # command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    working_dir: /root
    volumes:
      - ./volumes/meta/:/var/lib/docker/volumes
    networks:
      testing_net:
        ipv4_address: 172.19.1.8

networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
