version: '3'

services:

  kali:
    image: estopl/kali:laura
    tty: true
    cap_add:
      - NET_ADMIN
    working_dir: /test
    volumes:
      - kali/:/test
    networks:
      testing_net:
        ipv4_address: 172.19.0.3

  mutillidae_db:
    image: mysql:5.5
    environment:
        MYSQL_ROOT_PASSWORD: mutillidae
        MYSQL_DATABASE: mutillidae
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    networks:
      - testing_net

  mutillidae_web:
    image: crhystamils/mutillidae
    links:
        - mutillidae_db
    depends_on:
        - mutillidae_db
    networks:
      testing_net:
        ipv4_address: 172.19.1.3

  web_dvwa:
    image: vulnerables/web-dvwa
    networks:
      testing_net:
        ipv4_address: 172.19.1.4

  juice_shop:
    image: bkimminich/juice-shop
    networks:
      testing_net:
        ipv4_address: 172.19.1.5

  mysql:
    image: mysql:5
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    networks:
      testing_net:
        ipv4_address: 172.19.1.7

  wordpress:
    image: estopl/wordpress:laura
    depends_on:
      - mysql
    volumes:
      - wordpress_data:/var/www/html
    environment: 
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8080:80"
    networks:
      testing_net:
        ipv4_address: 172.19.1.6

  metasploitable2:
    tty: true
    image: estopl/metasploitable2-testing:latest
    # command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    working_dir: /test
    volumes:
      - meta/:/test
    networks:
      testing_net:
        ipv4_address: 172.19.1.8

volumes:
  kali: {}
  db_data: {}
  wordpress_data: {}
  meta: {}

networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
